name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Ali-Elshorpagi
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push to Output Branch
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }} # Replace with your PAT secret
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -B output
          git add .
          git commit -m "Auto-update data"
          git push https://github.com/Ali-Elshorpagi/Ali-Elshorpagi.git output
